
spring.datasource:
  url: jdbc:mysql://localhost:3306/shibboleth
  username: alloc
  password: allocDemo
 

spring.jpa.properties:
  hibernate.show_sql: true
  hibernate.ddl-auto: none
  
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

