
spring:
  datasource:
#   driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chouette.giprecia.net:3306/shibboleth?serverTimezone=Europe/Paris
    username: bourse
#  password: 
    
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate.ddl-auto: none
# pour permettre les majuscules dans les noms de colonne mysql:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  ldap:
    anonymous-read-only: false
    urls: ldap://pigeon.giprecia.net:389
    base: dc=esco-centre,dc=fr
    username: cn=sarapis,ou=administrateurs,dc=esco-centre,dc=fr
#   password: 
   
#csv.file.name: .........

shibbolet.entity:
  local: https://ent.netocentre.fr/idp/shibboleth
  peer: https://ent.yeps.fr/shibboleth

allowed.ip.list: 
#  extern: 192.168.57.117,
  intern: 127.0.0.1,

